# Generated by Django 6.0.6 on 2026-09-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสวิชา')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อวิชา')),
                ('year_level', models.IntegerField(choices=[(1, 'ปี 1'), (2, 'ปี 2'), (3, 'ปี 3'), (4, 'ปี 4')], verbose_name='ชั้นปี')),
                ('subject_type', models.CharField(choices=[('core', 'วิชาแกน/บังคับ'), ('elective', 'วิชาเลือก')], max_length=50, verbose_name='กลุ่มวิชา')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบายวิชา')),
            ],
            options={
                'verbose_name': 'วิชาในสาขา',
                'verbose_name_plural': 'วิชาในสาขา',
                'ordering': ['year_level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อสิ่งของ/ชีท')),
                ('category', models.CharField(choices=[('sheet', 'ชีทสรุป'), ('book', 'หนังสือเรียน'), ('tool', 'อุปกรณ์การเรียน/แล็บ'), ('etc', 'ของใช้ทั่วไป')], max_length=50, verbose_name='หมวดหมู่')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='ราคา (0 = แจกฟรี)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='รูปภาพประกอบ')),
                ('description', models.TextField(verbose_name='รายละเอียดสภาพของ/โน้ต')),
                ('status', models.CharField(choices=[('available', 'พร้อมส่งต่อ'), ('reserved', 'มีคนขอรับแล้ว'), ('completed', 'ส่งมอบสำเร็จ')], default='available', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ลงประกาศ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ลงประกาศ')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.subject', verbose_name='วิชาที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'ของใช้ / ชีทสรุป',
                'verbose_name_plural': 'ของใช้ / ชีทสรุป',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_place', models.CharField(max_length=150, verbose_name='จุดนัดรับใต้ตึกสาขา')),
                ('meetup_date', models.DateField(verbose_name='วันที่นัดรับ')),
                ('note', models.TextField(blank=True, verbose_name='ข้อความถึงรุ่นพี่/ผู้ให้')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='เจ้าของยืนยันการส่งมอบ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคำขอ')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอรับ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.item', verbose_name='ของที่ขอรับ')),
            ],
            options={
                'verbose_name': 'การขอนัดรับของ',
                'verbose_name_plural': 'การขอนัดรับของ',
                'ordering': ['-created_at'],
            },
        ),
    ]
