# Generated by Django 6.0.6 on 2026-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ลิงก์ช่องทางติดต่อ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('sheet', 'ชีทสรุป'), ('book', 'หนังสือเรียน'), ('tool', 'อุปกรณ์การเรียน/แล็บ'), ('etc', 'ของใช้ทั่วไป')], default='etc', max_length=50, verbose_name='หมวดหมู่'),
        ),
    ]
