# Generated by Django 6.0.6 on 2026-09-14 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_item_contact_link_alter_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('claim_new', 'มีคำขอนัดรับใหม่'), ('claim_confirmed', 'ยืนยันการส่งมอบแล้ว'), ('system', 'แจ้งเตือนระบบ')], default='claim_new', max_length=50, verbose_name='ประเภทการแจ้งเตือน')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่แจ้งเตือน')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.claimrequest', verbose_name='คำขอนัดรับ')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.item', verbose_name='สิ่งของที่เกี่ยวข้อง')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับการแจ้งเตือน')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่ง')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
    ]
