# Generated by Django 6.0.6 on 2026-09-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default='', max_length=20, verbose_name='รหัสนักศึกษา')),
                ('year_level', models.IntegerField(choices=[(1, 'ปี 1'), (2, 'ปี 2'), (3, 'ปี 3'), (4, 'ปี 4')], default=2, verbose_name='ชั้นปี')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('line_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Line ID')),
                ('bio', models.TextField(blank=True, default='', verbose_name='คำแนะนำตัวสั้นๆ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้',
            },
        ),
    ]
