# Generated by Django 6.0.6 on 2026-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(choices=[('blue', 'CS Blue'), ('indigo', 'Royal Indigo'), ('emerald', 'Emerald Forest'), ('rose', 'Rose Ruby'), ('amber', 'Amber Sun')], default='blue', max_length=20, verbose_name='สีธีมหลัก'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='รับการแจ้งเตือนทางอีเมล'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_contact_publicly',
            field=models.BooleanField(default=True, verbose_name='แสดงเบอร์โทร/Line ในหน้าประกาศ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'โหมดสว่าง'), ('dark', 'โหมดมืด'), ('system', 'ตามระบบ')], default='light', max_length=20, verbose_name='โหมดธีม'),
        ),
    ]
