# Generated by Django 6.0.6 on 2026-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_userprofile_accent_color_userprofile_notify_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='pickup_place',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='จุดนัดรับใต้ตึกสาขา'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'โหมดสว่าง'), ('dark', 'โหมดมืด')], default='light', max_length=20, verbose_name='โหมดธีม'),
        ),
    ]
