# Generated by Django 6.0.6 on 2026-09-16 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_alter_claimrequest_pickup_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('claim_new', 'มีคำขอนัดรับใหม่'), ('claim_confirmed', 'ยืนยันการส่งมอบแล้ว'), ('comment_new', 'มีความคิดเห็นใหม่'), ('reply_new', 'มีการตอบกลับความคิดเห็น'), ('system', 'แจ้งเตือนระบบ')], default='claim_new', max_length=50, verbose_name='ประเภทการแจ้งเตือน'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='ข้อความความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่แสดงความเห็น')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แสดงความเห็น')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='share.item', verbose_name='สิ่งของที่แสดงความเห็น')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='share.comment', verbose_name='ตอบกลับความคิดเห็น')),
            ],
            options={
                'verbose_name': 'ความคิดเห็น',
                'verbose_name_plural': 'ความคิดเห็น',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.comment', verbose_name='ความคิดเห็น'),
        ),
    ]
