# Generated by Django 6.0.6 on 2026-09-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_alter_notification_notification_type_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='pickup_place',
            field=models.CharField(choices=[('ใต้ตึกคณะ ICT (ลานกิจกรรม)', 'ใต้ตึกคณะ ICT (ลานกิจกรรม)'), ('หน้าห้องแล็บ CS ชั้น 2', 'หน้าห้องแล็บ CS ชั้น 2'), ('โรงอาหารกลาง / ลานเพลิน', 'โรงอาหารกลาง / ลานเพลิน'), ('หน้าร้านกาแฟ / หอสมุด', 'หน้าร้านกาแฟ / หอสมุด'), ('นัดหมายผ่านแชทส่วนตัว', 'นัดหมายผ่านแชทส่วนตัว')], default='ใต้ตึกคณะ ICT (ลานกิจกรรม)', max_length=150, verbose_name='จุดนัดรับใต้ตึกสาขา'),
        ),
    ]
