# Generated by Django 6.0.6 on 2026-09-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_alter_claimrequest_pickup_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
