# Generated by Django 6.0.6 on 2026-09-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_remove_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
